# Generated by Django 5.0 on 2023-12-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
